In [18]:
num = int(input("Enter an integer"))

Enter an integer9


In [19]:
for i in range(1,11):
  print(f'{num} x {i} = {num*i}')

9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


take two number and print the table of each

In [21]:
num1 = int(input("Enter an integer"))

Enter an integer89


In [22]:
for i in range(1,21):
  print(f'{num1} x {i} = {num1*i}')

89 x 1 = 89
89 x 2 = 178
89 x 3 = 267
89 x 4 = 356
89 x 5 = 445
89 x 6 = 534
89 x 7 = 623
89 x 8 = 712
89 x 9 = 801
89 x 10 = 890
89 x 11 = 979
89 x 12 = 1068
89 x 13 = 1157
89 x 14 = 1246
89 x 15 = 1335
89 x 16 = 1424
89 x 17 = 1513
89 x 18 = 1602
89 x 19 = 1691
89 x 20 = 1780


In [24]:
num2 = int(input("Enter an integer"))

Enter an integer56


In [25]:
for i in range(1,21):
  print(f'{num2} x {i} = {num2*i}')

56 x 1 = 56
56 x 2 = 112
56 x 3 = 168
56 x 4 = 224
56 x 5 = 280
56 x 6 = 336
56 x 7 = 392
56 x 8 = 448
56 x 9 = 504
56 x 10 = 560
56 x 11 = 616
56 x 12 = 672
56 x 13 = 728
56 x 14 = 784
56 x 15 = 840
56 x 16 = 896
56 x 17 = 952
56 x 18 = 1008
56 x 19 = 1064
56 x 20 = 1120


In [26]:
a= float(input("Enter first number"))
b=float(input("Enter secound number"))
print(f'Addition:{a+b}')
print(f'Subtraction:{a-b}')
print(f'Multiplcation:{a*b}')
print(f'Division:{a/b}')
print(f'Floor Division:{a//b}')
print(f'Modulus:{a%b}')
print(f'Exponent:{a**b}')

Enter first number89
Enter secound number45
Addition:134.0
Subtraction:44.0
Multiplcation:4005.0
Division:1.9777777777777779
Floor Division:1.0
Modulus:44.0
Exponent:5.2789834325329645e+87


In [27]:
num=[12,15,18,10,20]
total=0
for x in num:
  total +=x
print(total)
avg=total/len(num)
print(avg)

75
15.0


In [28]:
import numpy as np
marks=np.array([72,65,81,54,90])
print("Array:",marks)
print("Type:", type(marks))

Array: [72 65 81 54 90]
Type: <class 'numpy.ndarray'>


In [29]:
import numpy as np
marks=np.array([[72,65,81],
               [54,90,76]])
print(f'Array:\n{marks}')
print(f'Type:{type(marks)}')
print(f'dtype:{marks.dtype}')
print(f'Shape:{marks.shape}')
print(f'Size:{marks.size}')
print(f'Dimension:{marks.ndim}')

Array:
[[72 65 81]
 [54 90 76]]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(2, 3)
Size:6
Dimension:2


In [31]:
import numpy as np
marks=np.array([
    [72,65,81],
    [54,90,76],
    [67,87,58]
    ])
print(f'Array:\n{marks}')
print(f'Type:{type(marks)}')
print(f'dtype:{marks.dtype}')
print(f'Shape:{marks.shape}')
print(f'Size:{marks.size}')
print(f'Dimension:{marks.ndim}')

Array:
[[72 65 81]
 [54 90 76]
 [67 87 58]]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(3, 3)
Size:9
Dimension:2


In [30]:
import numpy as np
marks=np.array([[
    [72,65,81],
    [54,90,76],
    [67,87,58]
    ]])
print(f'Array:\n{marks}')
print(f'Type:{type(marks)}')
print(f'dtype:{marks.dtype}')
print(f'Shape:{marks.shape}')
print(f'Size:{marks.size}')
print(f'Dimension:{marks.ndim}')

Array:
[[[72 65 81]
  [54 90 76]
  [67 87 58]]]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(1, 3, 3)
Size:9
Dimension:3


In [32]:
arr=np.array(23)
print(f'Array:\n{arr}')
print(f'Type:{type(arr)}')
print(f'dtype:{arr.dtype}')
print(f'Shape:{arr.shape}')
print(f'Size:{arr.size}')
print(f'Dimension:{arr.ndim}')

Array:
23
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:()
Size:1
Dimension:0


In [33]:
arrs=np.array([23,53])
print(f'Array:\n{arrs}')
print(f'Type:{type(arrs)}')
print(f'dtype:{arrs.dtype}')
print(f'Shape:{arrs.shape}')
print(f'Size:{arrs.size}')
print(f'Dimension:{arrs.ndim}')

Array:
[23 53]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(2,)
Size:2
Dimension:1


In [34]:
print(f'First row:{marks[0]}')
print(f'Second row:{marks[1]}')
print(f'Third row:{marks[2]}')
print(f'First column:{marks[:,0]}')
print(f'Second column:{marks[:,1]}')
print(f'Third column:{marks[:,2]}')

First row:[72 65 81]
Second row:[54 90 76]
Third row:[67 87 58]
First column:[72 54 67]
Second column:[65 90 87]
Third column:[81 76 58]


In [35]:
print(f'Row 1, Column 1:{marks[0,0]}')
print(f'Row 1, Column 2:{marks[0,1]}')
print(f'Row 1, Column 3:{marks[0,2]}')
print(f'Row 2, Column 1:{marks[1,0]}')
print(f'Row 2, Column 2:{marks[1,1]}')
print(f'Row 2, Column 3:{marks[1,2]}')

Row 1, Column 1:72
Row 1, Column 2:65
Row 1, Column 3:81
Row 2, Column 1:54
Row 2, Column 2:90
Row 2, Column 3:76


In [36]:
import numpy as np

d3array = np.array([[[72,65,81], [4,5,6]],[[54,90,76], [7,8,9]], [[54,90,76], [10,11,12]]])
print(f'Array:\n{d3array}')
print(f'Type:{type(d3array)}')
print(f'dtype:{d3array.dtype}')
print(f'Shape:{d3array.shape}')
print(f'Size:{d3array.size}')
print(f'Dimension:{d3array.ndim}')

Array:
[[[72 65 81]
  [ 4  5  6]]

 [[54 90 76]
  [ 7  8  9]]

 [[54 90 76]
  [10 11 12]]]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(3, 2, 3)
Size:18
Dimension:3


In [37]:
np.array([[[0,1], [2,3]],[[4,5], [6,7]]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
arr1 = np.array([45,67,83,56,78,90,45,36])
print(f'First four:{arr1[:4]}')
print(f'Middle:{arr1[2:6]}')
print(f'Every second value:{arr1[::2]}')
print(f'Reverse:{arr1[::-1]}')

First four:[45 67 83 56]
Middle:[83 56 78 90]
Every second value:[45 83 78 45]
Reverse:[36 45 90 78 56 83 67 45]


In [39]:
print(f'Last four:{arr1[-4:]}')
print(f'Every second value from last:{arr1[-1::-2]}')

Last four:[78 90 45 36]
Every second value from last:[36 90 56 67]


Creating Array from Scartch

In [40]:
zeros = np.zeros(5)
ones = np.ones((2,3))
full =np.full((2,3),7)
print(f'Zeros:\n{zeros}')
print(f'Ones:\n{ones}')
print(f'Full:\n{full}')

Zeros:
[0. 0. 0. 0. 0.]
Ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Full:
[[7 7 7]
 [7 7 7]]


In [41]:
a = np.arange(0,10,2)
print(f'arange:{a}')

arange:[0 2 4 6 8]


In [42]:
b= np.linspace(0,10,6)

In [43]:
print(f'arange:{b}')

arange:[ 0.  2.  4.  6.  8. 10.]


In [44]:
c = np.linspace(0,1,11)
print(f'arange:{c}')

arange:[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [45]:
np.random.seed(42)
d=np.random.random(5)
print(d)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [46]:
np.random.seed(0)
e=np.random.randint(1,200,size=15)
print(e)

[173  48 118 193  68 196 104  10  22  37  88  71  89 141  59]
